# Generated by Django 4.1.3 on 2022-11-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empredimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celular", models.CharField(max_length=13, verbose_name="Celular")),
                ("telefono", models.CharField(max_length=20, verbose_name="telefono")),
                (
                    "direccion",
                    models.CharField(max_length=500, verbose_name="Direccion"),
                ),
                ("altitud", models.CharField(max_length=500, verbose_name="altitud")),
                ("latitud", models.CharField(max_length=500, verbose_name="latitud")),
                ("descripcion", models.TextField()),
                ("hora_Apertura", models.DateTimeField()),
                ("hora_cierre", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("cedula", "Cedula"), ("pasaporte", "Pasaporte")],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("cedula", models.CharField(max_length=13, verbose_name="Cedula")),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=200, verbose_name="Apellidos"),
                ),
                (
                    "correo_electronico",
                    models.EmailField(max_length=254, verbose_name="Correo"),
                ),
                ("celular", models.CharField(max_length=20, verbose_name="Celular")),
                (
                    "direccion",
                    models.CharField(max_length=500, verbose_name="Direccion"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_usuarios/",
                        verbose_name="Subir foto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administracion.persona",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_actualizacion", models.DateTimeField()),
                ("estado", models.BooleanField()),
            ],
            bases=("administracion.persona",),
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administracion.persona",
                    ),
                ),
                (
                    "pais_origen",
                    models.CharField(max_length=200, verbose_name="Pais de Origen"),
                ),
            ],
            bases=("administracion.persona",),
        ),
        migrations.CreateModel(
            name="Emprendedor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administracion.persona",
                    ),
                ),
            ],
            bases=("administracion.persona",),
        ),
    ]
